stellar:
  version: 1.33.1
  homepage: https://xaoxuu.com/wiki/stellar/
  repo: https://github.com/xaoxuu/hexo-theme-stellar
  main_css: /css/main.css
  main_js: /js/main.js
preconnect: null
canonical:
  closeEnable: true
  closeText: 关闭提示
  originalHost: null
  officialHosts:
  - localhost
open_graph:
  enable: true
  twitter_id: null
structured_data:
  links: []
logo:
  avatar: '[https://api.iconify.design/mdi:boxing-glove.svg](/)'
  title: '[{config.title}](/)'
  subtitle: '{config.subtitle}'
menubar:
  columns: 4
  items:
  - id: post
    theme: '#1BCDFC'
    icon: https://api.iconify.design/solar:documents-bold-duotone.svg
    title: 블로그
    url: /
  - id: notebooks
    theme: '#3DC550'
    icon: https://api.iconify.design/solar:notebook-bookmark-bold-duotone.svg
    title: 노트
    url: /notebooks/
  - id: archive
    theme: '#FA6400'
    icon: https://api.iconify.design/solar:calendar-bold-duotone.svg
    title: 아카이브
    url: /blog/archives/
  - id: tags
    theme: '#F44336'
    icon: https://api.iconify.design/solar:hashtag-square-bold.svg
    title: 태그
    url: /blog/tags/
site_tree:
  home:
    leftbar: welcome, recent
    rightbar: null
  index_blog:
    base_dir: blog
    menu_id: post
    leftbar: welcome, recent
    rightbar: null
    nav_tabs: null
  index_topic:
    base_dir: topic
    menu_id: post
  index_wiki:
    base_dir: wiki
    menu_id: wiki
    leftbar: related, recent
    rightbar: null
    nav_tabs: null
  post:
    menu_id: post
    leftbar: related, recent
    rightbar: ghrepo, toc
  topic:
    menu_id: post
  wiki:
    menu_id: wiki
    leftbar: tree, related, recent
    rightbar: ghrepo, toc
  notebooks:
    base_dir: notebooks
    menu_id: notebooks
    leftbar: recent
    rightbar: null
  notes:
    menu_id: notebooks
    leftbar: tagtree, recent
    rightbar: null
  note:
    leftbar: tagtree, recent
    rightbar: toc
  author:
    base_dir: author
    menu_id: post
    leftbar: recent, timeline
    rightbar: timeline
  error_page:
    menu_id: post
    '404': /404.html
    leftbar: recent, timeline
    rightbar: timeline
  page:
    leftbar: recent
    rightbar: toc
notebook:
  auto_excerpt: 128
  tagcons:
    ? ''
    : solar:hashtag-square-bold
  per_page: null
  order_by: -updated
  license: false
  share: false
article:
  type: tech
  indent: null
  cover_ratio: 2
  banner_ratio: 2.5
  auto_banner: false
  auto_excerpt: 128
  category_color:
    探索号: '#f44336'
  license: 本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/)
    许可协议，转载请注明出处。
  share: null
  related_posts:
    enable: false
    max_count: 5
search:
  service: local_search
  local_search:
    field: all
    path: /search.json
    content: true
    skip_search: null
  algolia_search:
    appId: null
    apiKey: null
    indexName: null
    js: https://gcore.jsdelivr.net/algoliasearch/3/algoliasearch.min.js
comments:
  service: null
  comment_title: 快来参与讨论吧~
  lazyload: false
  custom_css: null
  beaudar:
    repo: xxx/xxx
    issue-term: pathname
    issue-number: null
    theme: preferred-color-scheme
    label: null
    input-position: top
    comment-order: desc
    keep-theme: null
    loading: false
    branch: main
  utterances:
    repo: xxx/xxx
    issue-term: pathname
    issue-number: null
    theme: preferred-color-scheme
    label: null
  giscus:
    src: https://giscus.app/client.js
    data-repo: xxx/xxx
    data-repo-id: null
    data-category: null
    data-category-id: null
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: null
    crossorigin: anonymous
  twikoo:
    js: https://gcore.jsdelivr.net/npm/twikoo@1.6/dist/twikoo.all.min.js
    envId: https://xxx
  waline:
    js: https://gcore.jsdelivr.net/npm/@waline/client@3.1/dist/waline.js
    css: https://gcore.jsdelivr.net/npm/@waline/client@3.1/dist/waline.css
    meta_css: https://gcore.jsdelivr.net/npm/@waline/client@3.1/dist/waline-meta.css
    serverURL: https://waline.vercel.app
    commentCount: true
    pageview: false
  artalk:
    css: https://unpkg.com/artalk@2.9/dist/artalk.css
    js: https://unpkg.com/artalk@2.9/dist/artalk.js
    server: null
    site: ''
    darkMode: auto
    fancybox: true
    imageUploader: null
footer:
  social: null
  sitemap: null
  content: © {author.name} · Powered by {theme.name} {theme.version}
tag_plugins:
  note:
    default_color: ''
    border: true
  checkbox:
    interactive: false
  quot:
    default:
      prefix: bxs:quote-left
      suffix: bxs:quote-right
    hashtag:
      prefix: solar:hashtag-square-bold
    question:
      prefix: ph:seal-question-fill
  emoji:
    default: https://gcore.jsdelivr.net/gh/cdn-x/emoticons@3.1/qq/{name}.gif
    twemoji: https://gcore.jsdelivr.net/gh/twitter/twemoji/assets/svg/{name}.svg
    qq: https://gcore.jsdelivr.net/gh/cdn-x/emoticons@3.1/qq/{name}.gif
    aru: https://gcore.jsdelivr.net/gh/cdn-x/emoticons@3.1/aru/{name}.gif
    tieba: https://gcore.jsdelivr.net/gh/cdn-x/emoticons@3.1/tieba/{name}.png
    blobcat: https://gcore.jsdelivr.net/gh/cdn-x/emoticons@3.1/blobcat/{name}.gif
  icon:
    default_color: accent
  button:
    default_color: theme
  image:
    fancybox: false
  copy:
    toast: 复制成功
  timeline:
    max-height: 80vh
  mark:
    default_color: yellow
  hashtag:
    default_color: null
  okr:
    border: true
    status:
      in_track:
        color: blue
        label: 正常
      at_risk:
        color: yellow
        label: 风险
      off_track:
        color: orange
        label: 延期
      finished:
        color: green
        label: 已完成
      unfinished:
        color: red
        label: 未完成
  gallery:
    layout: grid
    size: mix
    ratio: square
  chat:
    api: https://siteinfo.listentothewind.cn/api/v1
dependencies:
  jquery: https://gcore.jsdelivr.net/npm/jquery@3.7/dist/jquery.min.js
  marked: https://gcore.jsdelivr.net/npm/marked@13.0/lib/marked.umd.min.js
  lazyload:
    js: https://gcore.jsdelivr.net/npm/vanilla-lazyload@19.1/dist/lazyload.min.js
    transition: fade
    fix_ratio: true
data_services:
  mdrender:
    js: /js/services/mdrender.js
  siteinfo:
    js: /js/services/siteinfo.js
    api: null
  ghinfo:
    js: /js/services/ghinfo.js
  rating:
    js: /js/services/rating.js
    api: https://star-vote.xaox.cc/api/rating
  vote:
    js: /js/services/vote.js
    api: https://star-vote.xaox.cc/api/vote
  sites:
    js: /js/services/sites.js
  friends:
    js: /js/services/friends.js
  friends_and_posts:
    js: /js/services/friends_and_posts.js
  timeline:
    js: /js/services/timeline.js
  fcircle:
    js: /js/services/fcircle.js
  weibo:
    js: /js/services/weibo.js
  memos:
    js: /js/services/memos.js
  voice:
    js: /js/plugins/voice.js
  video:
    js: /js/plugins/video.js
  download-file:
    js: /js/plugins/download-file.js
  twikoo:
    js: /js/services/twikoo_latest_comment.js
  waline:
    js: /js/services/waline_latest_comment.js
  artalk:
    js: /js/services/artalk_latest_comment.js
  giscus:
    js: /js/services/giscus_latest_comment.js
  contributors:
    edit_this_page:
      _posts/: null
      wiki/stellar/: https://github.com/xaoxuu/hexo-theme-stellar-docs/blob/main/
    js: /js/services/contributors.js
  rss:
    js: /js/services/rss.js
plugins:
  preload:
    enable: true
    service: flying_pages
    flying_pages: https://gcore.jsdelivr.net/npm/flying-pages@2/flying-pages.min.js
  pjax:
    enable: false
    selectors:
    - title
    - '#l_cover'
    - .l_body
    timeout: 10000
    cacheBust: false
    nprogress: true
  fancybox:
    enable: true
    js: https://gcore.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js
    css: https://gcore.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css
    selector: .timenode p>img
  swiper:
    enable: true
    css: https://unpkg.com/swiper@10.3/swiper-bundle.min.css
    js: https://unpkg.com/swiper@10.3/swiper-bundle.min.js
  scrollreveal:
    enable: null
    js: https://gcore.jsdelivr.net/npm/scrollreveal@4.0/dist/scrollreveal.min.js
    distance: 8px
    duration: 1000
    interval: 100
    scale: 1
  tianli_gpt:
    enable: null
    js: https://jsd.onmicrosoft.cn/gh/qxchuckle/Post-Summary-AI@6.0/chuckle-post-ai.min.js
    field: post
    key: 5Q5mpqRK5DkwT1X9Gi5e
    total_length: 1000
    typewriter: true
    summary_directly: true
    rec_method: all
    hide_shuttle: true
    summary_toggle: false
    interface:
      name: AI摘要
      introduce: '我是文章辅助AI: QX-AI，点击下方的按钮，让我生成本文简介、推荐相关文章等。'
      version: TianliGPT
      button:
      - 介绍自己
      - 推荐文章
      - 生成摘要
      - 矩阵穿梭
  katex:
    enable: null
    inject: '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.23/dist/katex.min.css"
      integrity="sha384-//SZkxyB7axjCAopkAL1E1rve+ZSPKapD89Lo/lLhcsXR+zOYl5z6zJZEFXil+q0"
      crossorigin="anonymous">

      '
  mathjax:
    v3: false
    enable: null
    js: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  mermaid:
    enable: null
    style_optimization: false
    js: https://gcore.jsdelivr.net/npm/mermaid@v9/dist/mermaid.min.js
    theme: neutral
  copycode:
    enable: true
    default_text: Copy
    success_text: Copied
    toast: 复制成功
  heti:
    enable: false
    css: https://unpkg.com/heti@0.9/umd/heti.min.css
    js: https://unpkg.com/heti@0.9/umd/heti-addon.min.js
style:
  prefers_theme: auto
  smooth_scroll: true
  font-size:
    root: 16px
    body: 17px
    code: 85%
    codeblock: 0.8125rem
  font-family:
    body: system-ui, "Microsoft Yahei", "Segoe UI", Arial, sans-serif
    code: Menlo, Monaco, Consolas, system-ui, monospace, sans-serif
    codeblock: Menlo, Monaco, Consolas, system-ui, monospace, sans-serif
  text-align: left
  prefix:
    h2: https://api.iconify.design/ci:heading-h2.svg
  border-radius:
    card-l: 24px
    card: 16px
    card-s: 12px
    bar: 8px
    image-l: 24px
    image: 16px
    image-s: 8px
  color:
    theme: hsl(192 98% 55%)
    accent: hsl(14 100% 57%)
    link: hsl(207 90% 54%)
  animated_avatar:
    animate: auto
    background: https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/avatar/round/rainbow64@3x.webp
  codeblock:
    scrollbar: 4px
    highlightjs_theme: https://gcore.jsdelivr.net/gh/highlightjs/cdn-release@11.9/build/styles/atom-one-dark.min.css
  loading:
    loading: 正在加载
    error: 加载失败，请稍后重试。
  gradient:
    start: linear-gradient(to right, hsl(215, 95%, 64%), hsl(195, 95%, 60%), hsl(165,
      95%, 56%), hsl(165, 95%, 56%), hsl(195 95% 60%), hsl(215, 95%, 64%))
  leftbar:
    background-color-light: var(--card)
    background-color-dark: var(--card)
    background-image: url(https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.13/image/sidebar-bg1@small.jpg)
    blur-px: 100px
    blur-bg: var(--bg-a60)
    background-opacity: 0.8
  paginator:
    prev: https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/arrow/f049bbd4e88ec.svg
    next: https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/arrow/064b95430caf4.svg
  error_page: https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/404/1c830bfcd517d.svg
  site:
    blur-px: 100px
    blur-bg: var(--bg-a75)
    blur-sat: 300%
  header_prefix:
    h2: '#'
    h3: '='
    h4: '|'
    h5: ':'
default:
  avatar: https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/avatar/round/3442075.svg
  link: https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/link/8f277b4ee0ecd.svg
  cover: https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/cover/76b86c0226ffd.svg
  image: https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/image/2659360.svg
  project: https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/image/2779789.png
  banner: https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/banner/books.jpg
  topic: https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.12/image/10433048.png
  loading: https://api.iconify.design/eos-icons:three-dots-loading.svg?color=%231cd0fd
  image_onerror: data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='2rem'
    height='2rem' viewBox='0 0 24 24'%3E%3C!-- Icon from Solar by 480 Design - https://creativecommons.org/licenses/by/4.0/
    --%3E%3Cpath fill='%23F44336' d='M22 12.698c-.002 1.47-.013 2.718-.096 3.743c-.097
    1.19-.296 2.184-.74 3.009a4.2 4.2 0 0 1-.73.983c-.833.833-1.893 1.21-3.237 1.39C15.884
    22 14.2 22 12.053 22h-.106c-2.148 0-3.83 0-5.144-.177c-1.343-.18-2.404-.557-3.236-1.39c-.738-.738-1.12-1.656-1.322-2.795c-.2-1.12-.236-2.512-.243-4.241Q1.999
    12.737 2 12v-.054c0-2.148 0-3.83.177-5.144c.18-1.343.557-2.404 1.39-3.236s1.893-1.21
    3.236-1.39c1.168-.157 2.67-.175 4.499-.177a.697.697 0 1 1 0 1.396c-1.855.002-3.234.018-4.313.163c-1.189.16-1.906.464-2.436.994S3.72
    5.8 3.56 6.99C3.397 8.2 3.395 9.788 3.395 12v.784l.932-.814a2.14 2.14 0 0 1 2.922.097l3.99
    3.99a1.86 1.86 0 0 0 2.385.207l.278-.195a2.79 2.79 0 0 1 3.471.209l2.633 2.37c.265-.557.423-1.288.507-2.32c.079-.972.09-2.152.091-3.63a.698.698
    0 0 1 1.396 0' opacity='.5'/%3E%3Cpath fill='%23F44336' fill-rule='evenodd' d='M17.5
    11c-2.121 0-3.182 0-3.841-.659S13 8.621 13 6.5s0-3.182.659-3.841S15.379 2 17.5
    2s3.182 0 3.841.659S22 4.379 22 6.5s0 3.182-.659 3.841S19.621 11 17.5 11m-1.47-7.03a.75.75
    0 1 0-1.06 1.06l1.47 1.47l-1.47 1.47a.75.75 0 0 0 1.06 1.06l1.47-1.47l1.47 1.47a.75.75
    0 1 0 1.06-1.06L18.56 6.5l1.47-1.47a.75.75 0 0 0-1.06-1.06L17.5 5.44z' clip-rule='evenodd'/%3E%3C/svg%3E
api_host:
  ghapi: api.github.com
  ghraw: raw.githubusercontent.com
  gist: gist.github.com
  ghcard: github-readme-stats.vercel.app
system:
  override_pretty_urls: true
